# see roles/network_plugin/cilium/defaults/main.yml
# https://github.com/cilium/cilium/tree/v1.9.6/install/kubernetes/cilium
# kube_apiserver_global_endpoint:

cilium_bpf_ncc_enabled: true
cilium_config_loadBalancer_algorithm: "maglev"
cilium_config_maglev_tableSize: "65521"
cilium_config_maglev_hashSeed: "SEED"
cilium_tunnel_mode: "disabled"
cilium_config_tunnel: "disabled"
cilium_config_autoDirectNodeRoutes: "true"
cilium_config_kubeProxyReplacement: "strict"
cilium_config_loadBalancer_mode: "dsr"
cilium_config_loadBalancer_acceleration: "native"
cilium_config_device: "{eth4,eth5}"
cilium_config_lbMapMax: 131072
